analytics: {}
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.726973
  lightness: 0.146675
  rhythmicContrast: 0.480263
  saturation: 0.737861
cta: {}
layout_spectrum: 0.914473
name: trafo.xyz blog
opengraph: {}
purpose: {}
typography_spectrum: 0.8761955928654567
